# Copyright (c) 2015-2019 RunSafe Security Inc.
import os

Import('env')

trapinfo_env = env.Clone()
trapinfo_env.Append(CPPPATH = ['../', './'])
trapinfo_env.Append(LIBS = ['elf', 'z'])
trapinfo_env.Append(LINKFLAGS = ['-static'])

if 'LIBELF_PATH' in trapinfo_env:
    libelf_inc_path = os.path.join(trapinfo_env['LIBELF_PATH'], "include")
    libelf_lib_path = os.path.join(trapinfo_env['LIBELF_PATH'], "lib")
    trapinfo_env.Append(CPPPATH = [libelf_inc_path])
    trapinfo_env.Append(LIBPATH = [libelf_lib_path])

trapinfo_env.Program('trapdump', ['TrapDump.c',
                                  '%s/ReadTrap.c' % env['PLATFORM']])

files = [Glob('trapdump')]

Return('files')
