# Copyright (c) 2015-2019 RunSafe Security Inc.
Import('env')

SOURCES = ['util/hash_32a.c', 'RandoLib.cpp', 'util/strtol.c', 'util/qsort.c',
           'util/printf.cpp', 'arch/%s/Util.cpp' % env['TARGET_ARCH']]

SOURCES = [Glob(f) for f in SOURCES] # Replace source files with full paths
files = SConscript(dirs=[env['PLATFORM']], exports=['env', 'SOURCES'], duplicate=0)
Return('files')

