# Copyright (c) 2015-2019 RunSafe Security Inc.
Import('env')

# FIXME: LIBPATH shouldn't be hardcoded like this
files = env.Program('TrapLib', ['TrapLib.cpp', 'stdafx.cpp'],
                     LIBS=['TrapCommon'],
                     LIBPATH=['../TrapCommon'])
Return('files')
