# Copyright (c) 2015-2019 RunSafe Security Inc.
Import('env')

SUBDIRS = ['LibWrapper',
           'LinkWrapper',
           'PatchEntry',
           'TrapCommon',
           'TrapLib',
           'TrapObj',
           'WrapperCommon']

files = SConscript(dirs=SUBDIRS, exports=['env'], duplicate=0)
Return('files')
