# Copyright (c) 2015-2019 RunSafe Security Inc.
Import('env')

files = env.Program('link', ['LinkWrapper.cpp', 'stdafx.cpp'],
                    LIBS=['WrapperCommon', 'TrapCommon'], 
                    LIBPATH=['../WrapperCommon',
                             '../TrapCommon'])
Return('files')
