#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

TC_PATH="$(readlink -e $(dirname "$0"))"
source $TC_PATH/functions.sh

run_original -B"$TC_PATH" -ffunction-sections -fdata-sections -fPIC "$@"
