#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

TC_PATH="$(readlink -e $(dirname "$0"))"
: ${TRAPLINKER_SR_ARCH:="x86_64"}        # only set if unset
: ${TRAPLINKER_SR_PATH:=$(readlink -f "$TC_PATH/../../out/$TRAPLINKER_SR_ARCH/bin")}
source $TC_PATH/functions.sh
SCRIPTS_PATH=$(readlink -f "$TC_PATH/../../scripts")

WRAPPER=`basename $0`
: ${TRAPLINKER_ORIG_LD:=`find_original`} # only set if unset
: ${TRAPLINKER_EXTRA_LDFLAGS:=}          # same as above
if [ -f /tmp/traplinker-argtrace ]; then
  "$SCRIPTS_PATH/argtrace.py" -rpath "$TRAPLINKER_SR_PATH" \
      -rpath "$TRAPLINKER_SR_PATH/$TRAPLINKER_SR_ARCH" \
      --traplinker-original-linker "$TRAPLINKER_ORIG_LD" \
      $TRAPLINKER_EXTRA_LDFLAGS "$@"
fi
exec_traplinker "$TRAPLINKER_SR_PATH/$WRAPPER" -rpath "$TRAPLINKER_SR_PATH" \
    -rpath "$TRAPLINKER_SR_PATH/$TRAPLINKER_SR_ARCH" \
    --traplinker-original-linker "$TRAPLINKER_ORIG_LD" \
    $TRAPLINKER_EXTRA_LDFLAGS "$@"
