# Copyright (c) 2015-2019 RunSafe Security Inc.
Import('env', 'SOURCES')

SOURCES.extend(['OSImpl.cpp',
                '%s/EntryPoint.asm' % env['TARGET_ARCH'],
                '%s/TrapHeader.asm' % env['TARGET_ARCH'],
                '%s/Relocation.cpp' % env['TARGET_ARCH']])

lib_env = env.Clone()
lib_env.Append(CPPPATH = '#/RandoLib')

#FIXME: is this only needed for EntryPoint.asm???
lib_env.Append(ASFLAGS = '/safeseh')

# Special compiler flags for RandoLib
lib_env.Append(CCFLAGS = '/Gd')   # Use cdecl calling convention
lib_env.Append(CCFLAGS = '/sdl-') # Disable security checks
lib_env.Append(CCFLAGS = '/GS-')  # Disable buffer overflow checks
lib_env.Append(CCFLAGS = '/GR-')  # No RTTI
lib_env.Append(CCFLAGS = '/Zl')   # Remove default library name

# Librarian flags
lib_env.Append(ARFLAGS = '/NODEFAULTLIB') # Don't include default libs

lib_env.Library('RandoLib', SOURCES)
files = Glob('RandoLib.lib')

Return('files')

