# Copyright (c) 2015-2019 RunSafe Security Inc.
Import('env')

# FIXME: LIBPATH shouldn't be hardcoded like this
files = env.Program('lib', ['LibWrapper.cpp', 'stdafx.cpp'],
                    LIBS=['WrapperCommon'],
                    LIBPATH=['../WrapperCommon']) 
Return('files')
